### ISSUE TITLE
Docs: Help with labeling workflow?

### ISSUE THREAD

**Issue by arnicas** [TutteInstitute/thisnotthat#44]
Hi - I don't understand the docs on the labelwidget and/or tags :).  I want to be able to select with lasso, and assign an existing label to them. Or create a new one.  I am having all sorts of trouble selecting existing labels and applying, 
or even making a new one and applying it. And I'm not sure what it's impacting -- not only the selected ones, I think. Is there a demo of this somewhere, or can you give me some tips?

Lynn

**Comment by jc-healy** [comment]
We're working on a video tutorial to show this in better detail.  We're hoping to put that out in January 2024.  Hopefully it will help with this.  Labeling is hard to explain with static text documentation.  Sorry about that.

**Comment by lmcinnes** [comment]
Hi Lynn, sorry about the delay, but we are not great at videos. A colleague helped out (as in, did the work for us) and we now have some better docs on the [LabelEditorWidget](https://thisnotthat.readthedocs.io/en/latest/label_editor_widget.html) and the [TagWidget](https://thisnotthat.readthedocs.io/en/latest/tag_widget.html) which includes some screen-capture videos of things in action. Hopefully that helps out?

**Comment by arnicas** [comment]
Lol - yes, it's a huge help. Believe it or not, I was just this morning trying to get ChatGPT to help me make this for myself. It's like working with a junior programmer.  Thank you so much and thank your colleague, please.

**Comment by arnicas** [comment]
cheers!
