### ISSUE TITLE
AttributeError: module 'thisnotthat' has no attribute 'Labeler'

### ISSUE THREAD

**Issue by elena-theresa-weber** [TutteInstitute/thisnotthat#7]
Hey all, 

I was trying to go through your example notebook and stumbled upon the following error: 
AttributeError: module 'thisnotthat' has no attribute 'Labeler'

after I ran this code snippet:
```
lb = tnt.Labeler(data, labels, hover=hover)
lb
```

I tried to look through your code to determine if the name of Labeler has changed but was not successful - any tips on how to fix it? 

Thank you!
Elena

**Comment by jc-healy** [comment]
Sorry that we missed this issue.  The Labeler has indeed changed.  I think you were looking for the LabelEditorWidget.   Here are a couple of examples of the current usage.

https://thisnotthat.readthedocs.io/en/latest/label_editor_widget.html
https://thisnotthat.readthedocs.io/en/latest/using_notebooks.html#tnt-as-a-bulk-labeller
